name = "user-mgmt"
main = "src/index.ts"
compatibility_date = "2024-01-17"


[[services]]
binding = "sessionService"
service = "session-state"

[[d1_databases]]
binding = "usersDB"
database_name = "users"
database_id = "<YOUR_DB_ID>"
